### ISSUE TITLE
Fix me first

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/ORGRep#1]

**Comment by status-open-bounty** [comment]
Balance: 0.1000 ETH
Tokens: SNT: 0.00
Contract address: [0x30e8e32b63e50cc1dd65d1b8419e013d776aa3ec](https://ropsten.etherscan.io/address/0x30e8e32b63e50cc1dd65d1b8419e013d776aa3ec)
Network: Testnet (Ropsten)
Paid to: annadanchenko
