### ISSUE TITLE
Closed Issue from test02

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/ORGRep#11]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x9116056375cbcb3100a0fc7aa7c07cda1eb95e36](https://ropsten.etherscan.io/address/0x9116056375cbcb3100a0fc7aa7c07cda1eb95e36)
![QR Code](https://openbounty.status.im:444/qr/CommitethTesters/ORGRep/bounty/11/84a935e6371181152ef41e681346228f70097bb375ef3923dba87e625ed0dad8/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
