### ISSUE TITLE
Demo issue here

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/ORGRep#21]

**Comment by status-open-bounty** [comment]
Current balance: 0.02 ETH
Contract address: [0xfe01451fd6a8abc9f51708cebcdbe155ebb6da58](https://ropsten.etherscan.io/address/0xfe01451fd6a8abc9f51708cebcdbe155ebb6da58)
![QR Code](https://openbounty.status.im:444/qr/CommitethTesters/ORGRep/bounty/21/b30abdcc3e9a1733762a6508b5ec3ac51acd5925ee2f093d58ad7b7878dfdcb5/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
