### ISSUE TITLE
fix me second

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/ORGRep#3]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xa9d4cb6ad2f05e161d06f6ed2c56d79d959856d0](https://ropsten.etherscan.io/address/0xa9d4cb6ad2f05e161d06f6ed2c56d79d959856d0)
Network: Testnet (Ropsten)
Paid to: annadanchenko
