### ISSUE TITLE
Issue number is in the commit comment

### ISSUE THREAD

**Issue by anna02test** [CommitethTesters/ORGRep#5]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x7165fdbf2e976852e7d2413513794a23faaf87ab](https://ropsten.etherscan.io/address/0x7165fdbf2e976852e7d2413513794a23faaf87ab)
Network: Testnet (Ropsten)
Paid to: annadanchenko
