### ISSUE TITLE
Handle いろはにほへと`~@#$%^&*()_+|-=\{}[]:”;’<>?,./®©£¥¢¦§«»€ &quot; &apos; &amp; &lt; &gt javascript:alert(‘1’);

### ISSUE THREAD

**Issue by anna01test** [CommitethTesters/ORGRep#7]
Handle いろはにほへと`~@#$%^&*()_+|-=\{}[]:”;’<>?,./®©£¥¢¦§«»€ &quot; &apos; &amp; &lt; &gt javascript:alert(‘1’);

**Comment by status-open-bounty** [comment]
Balance: 0.2400 ETH
Contract address: [0xb80b92bd0ebe75698900fbc43801685af128f076](https://ropsten.etherscan.io/address/0xb80b92bd0ebe75698900fbc43801685af128f076)
Network: Testnet (Ropsten)
Paid to: annadanchenko
